export const data = [
  {
    id: 3,
    name: "Burg",
    address: "USA",
    email: "bobrallaghan0@wunderground.com",
    status: "Active",
    phone: "798-196-1529",
    rating: 4.5,
  },
  {
    id: 2,
    name: "Hatti",
    address: "Ireland",
    email: "hduval1@amazon.com",
    status: "Active",
    phone: "888-299-9133",
    rating: 4.9,
  },
  {
    id: 1,
    name: "Beverlie",
    address: "France",
    email: "bpersicke2@elegantthemes.com",
    status: "Inactive",
    phone: "337-717-0253",
    rating: 4.2,
  },
  {
    id: 5,
    name: "Rodie",
    address: "USA",
    email: "rlghan3@disqus.com",
    status: "Active",
    phone: "265-350-5288",
    rating: 4.0,
  },
  {
    id: 4,
    name: "Christoforo",
    address: "Ireland",
    email: "cbockett4@walmart.com",
    status: "Inactive",
    phone: "569-547-2926",
    rating: 4.1,
  },
  {
    id: 7,
    name: "Antonia",
    address: "UK",
    email: "amcwhinnie5@chron.com",
    status: "Inactive",
    phone: "766-381-3144",
    rating: 4.1,
  },
  {
    id: 6,
    name: "Keefe",
    address: "USA",
    email: "kduckwith6@so-net.ne.jp",
    status: "Active",
    phone: "493-136-3466",
    rating: 5.0,
  },
  {
    id: 9,
    name: "Vergil",
    address: "UK",
    email: "vsheen7@ycombinator.com",
    status: "Active",
    phone: "428-490-8833",
    rating: 4.8,
  },
  {
    id: 8,
    name: "Merrill",
    address: "USA",
    email: "mevenden8@answers.com",
    status: "Active",
    phone: "294-236-1636",
    rating: 4.7,
  },
  {
    id: 10,
    name: "Linus",
    address: "UK",
    email: "lgrosvenor9@jiathis.com",
    status: "Active",
    phone: "415-392-6972",
    rating: 4.2,
  },
];
