name: Cache demo and Context
on: workflow_dispatch
jobs:
  # This example to get context will not work if we have many jobs, steps and actions
  # print:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Print context
  #       run: echo "${{ toJSON(github) }}"
  #     - name: Print context event
  #       run: echo "${{ toJSON(github.event) }}"
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache deps
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependancies
        run: npm ci
      # run: npm test
      - name: Test code
        run: npm run test2
  build:
    runs-on: ubuntu-latest
    # needs: [print, check]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache deps
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependancies
        run: npm ci
      - name: Build application
        run: echo Building some app ...
      # run: npm run build
      - name: Deploy
        run: echo Deploying...
      # run: npm run deploy
  printContext:
    runs-on: ubuntu-latest
    steps:
      - name: Print context
        env:
          PARAMS_GIT: ${{ toJSON(github) }}
        run: echo $PARAMS_GIT
      - name: Print context event
        env:
          PARAMS_EVENT: ${{ toJSON(github.event) }}
        run: echo $PARAMS_EVENT
