name: Check 2 Workflow
on: workflow_dispatch
jobs:
  super-lint:
    # name: Lint code base
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  Check:
    # needs: [super-lint]
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      #   - run: npm ci
      #   - run: npm test
      - name: Test code
        run: npm run test2
