name: Check 2 Workflow
on: workflow_dispatch
jobs:
  super-lint:
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  Check:
    # needs: [super-lint]
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependancies
        run: npm ci
        # run: npm test
      - name: Test code
        run: npm run test2
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependancies
        run: npm ci
      - name: Build application
        run: echo Building some app ...
        # run: npm run build
      - name: Deploy
        run: echo Deploying...
        # run: npm run deploy
