name: SuperTest check
on: workflow_dispatch
jobs:
  get-code:
    name: get code from GitHub
    runs-on: ubuntu-latest
    steps:
      - name: print to console
        run: echo Starting my workflow!

      - name: Node
        uses: actions/setup-node@v3
        
      - name: Get code from Repo
        uses: actions/checkout@v4

      - name: open correct Repo
        run: cd MySQL-database

      - name: Install deps
        run: npm ci

      - name: SuperTest
        run: npm run test
