name: SuperTest check
on: workflow_dispatch
jobs:
  get-code:
    name: get code from GitHub
    runs-on: ubuntu-latest
    steps:
      - name: print to console
        run: echo Starting my workflow!

      - name: Get code from Repo
        uses: actions/checkout@v4

      - name: open correct Repo
        run: cd MySQL-database

      # - name: Super-Linter
      #   uses: super-linter/super-linter@v7.2.1

      - name: Install dependencies
        run: npm ci

      - name: start server
        run: npm run start

      - name: SuperTest
        run: npm run test
